name: cinemapedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animate_do: ^4.2.0
  card_swiper: ^3.0.1
  dio: ^5.8.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.0
  intl: ^0.20.2
  isar: 
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  path: ^1.9.1
  path_provider: ^2.1.3
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: 
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - .env
